!Chart
XAxisConfigurations: 
-  axisStyleConfiguration: 
      axisColor: null
      labelColor: 777777
      markerColor: null
   position: MAXIMUM
YAxisConfigurations: 
-  axisStyleConfiguration: 
      axisColor: null
      labelColor: 777777
      markerColor: null
YWindowMaximum: 0.0
YWindowMinimum: -90.0
dataRendererConfigurations: 
-  areaDrawStyleConfiguration: 
      color: 15-63-255
   base: 0.0
   key: Record high
   type: bar
   width: 11
-  areaDrawStyleConfiguration: 
      borderColor: 0-0-255
      color: 190-190-255
   height: 5
   key: Average high
   type: rectangle
   width: 25
-  areaDrawStyleConfiguration: 
      borderColor: 0-0-255
      color: 30-128-240
   base: 0.0
   key: Daily mean
   type: bar
   width: 25
-  areaDrawStyleConfiguration: 
      image: http://clipart-library.com/image_gallery/33853.png
   height: 30
   key: Average low
   width: 30
-  areaDrawStyleConfiguration: 
      borderColor: 0-0-178
      colors: 
      - 0-0-255
      - 255-255-255
   key: Record low
   points: 8
   type: star
leftOffset: 30
legendPosition: 
   x: 450
   y: 50
rightMargin: 115
rightOffset: 30
title: South Pole Temperatures
topMargin: 50
width: 550
