axisStyleDefaults:
   axisColor: null
   labelColor: 777777
   markerColor: null
XAxes: 
-  axisStyle: 
   position: MAXIMUM
YAxes: 
-  axisStyle: 
   position: MINIMUM
YWindowMaximum: 0.0
YWindowMinimum: -90.0
graphs: 
   Daily mean: 
      graphDrawStyle: 
         borderColor: 0-0-255
         color: 30-128-240
      base: 0.0
      type: bar
      width: 25
   Average low: 
      graphDrawStyle: 
         image: http://clipart-library.com/image_gallery/33853.png
      height: 30
      width: 30
   Record high: 
      graphDrawStyle: 
         color: 15-63-255
      base: 0.0
      type: bar
      width: 11
   Record low: 
      graphDrawStyle: 
         borderColor: 0-0-178
         colors: 
         - 0-0-255
         - 255-255-255
      points: 8
      type: star
   Average high: 
      graphDrawStyle: 
         borderColor: 0-0-255
         color: 190-190-255
      height: 5
      type: rectangle
      width: 25
leftOffset: 30
legendPosition: 
   x: 450
   y: 50
tooltipFormat: '{n} {x}: {y}'
rightMargin: 115
rightOffset: 30
title: South Pole Temperatures
topMargin: 50
width: 550
